/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	chartv1alpha1 "github.com/jenkins-x-plugins/jx-charter/pkg/apis/chart/v1alpha1"
	versioned "github.com/jenkins-x-plugins/jx-charter/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x-plugins/jx-charter/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x-plugins/jx-charter/pkg/client/listers/chart/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChartInformer provides access to a shared informer and lister for
// Charts.
type ChartInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ChartLister
}

type chartInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewChartInformer constructs a new informer for Chart type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChartInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChartInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredChartInformer constructs a new informer for Chart type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChartInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChartV1alpha1().Charts(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChartV1alpha1().Charts(namespace).Watch(context.TODO(), options)
			},
		},
		&chartv1alpha1.Chart{},
		resyncPeriod,
		indexers,
	)
}

func (f *chartInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChartInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chartInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&chartv1alpha1.Chart{}, f.defaultInformer)
}

func (f *chartInformer) Lister() v1alpha1.ChartLister {
	return v1alpha1.NewChartLister(f.Informer().GetIndexer())
}
