{{ if .Values.clusterrole.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
{{- if .Values.serviceaccount.customName }}
  name: {{ .Values.serviceaccount.customName }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
